// Maps ingredient substring keys to filenames in the ingredient-images bucket (without .png)
// IMPORTANT: Order matters – more specific keys must come before generic ones
// e.g. "tomato paste" before "tomato", "chicken breast" before "chicken"
const INGREDIENT_IMAGE_MAP: Record<string, string> = {
  // --- Composite / specific (must be before their generic counterparts) ---
  'chicken breast': 'chicken-breast',
  'chicken thigh': 'chicken-thighs',
  'chicken stock': 'chicken-stock',
  'beef stock': 'beef-stock',
  'beef mince': 'minced-beef',
  'beef fillet': 'beef-fillet',
  'minced beef': 'minced-beef',
  'ground beef': 'minced-beef',
  'ground pork': 'ground-pork',
  'tomato paste': 'tomato-puree',
  'tomato puree': 'tomato-puree',
  'tomato sauce': 'tomato-sauce',
  'tomato ketchup': 'tomato-ketchup',
  'chopped tomato': 'chopped-tomatoes',
  'crushed tomato': 'chopped-tomatoes',
  'tinned tomato': 'chopped-tomatoes',
  'canned tomato': 'chopped-tomatoes',
  'passata': 'passata',
  'vegetable stock': 'vegetable-stock',
  'stock cube': 'vegetable-stock-cube',
  'bouillon': 'beef-stock',
  'spring onion': 'spring-onions',
  'red onion': 'red-onions',
  'garlic powder': 'garlic-powder',
  'smoked paprika': 'smoked-paprika',
  'cayenne': 'cayenne-pepper',
  'black pepper': 'black-pepper',
  'chilli powder': 'chilli-powder',
  'chilli flakes': 'chilli-flakes',
  'italian seasoning': 'italian-seasoning',
  'fish sauce': 'fish-sauce',
  'soy sauce': 'soy-sauce',
  'coconut milk': 'coconut-milk',
  'sesame oil': 'sesame-oil',
  'olive oil': 'olive-oil',
  'peanut oil': 'peanut-oil',
  'rice vinegar': 'rice-vinegar',
  'balsamic vinegar': 'balsamic-vinegar',
  'white wine vinegar': 'white-wine-vinegar',
  'red wine': 'red-wine',
  'white wine': 'white-wine',
  'sour cream': 'sour-cream',
  'cream cheese': 'cream-cheese',
  'brown sugar': 'brown-sugar',
  'caster sugar': 'caster-sugar',
  'icing sugar': 'icing-sugar',
  'sweet potato': 'sweet-potato',
  'dijon mustard': 'dijon-mustard',
  'wholegrain mustard': 'wholegrain-mustard',
  'mozzarella': 'mozzarella',
  'cheddar': 'cheddar-cheese',
  'feta': 'feta',
  'bay leaves': 'bay-leaves',
  'coriander': 'coriander',
  'parsley': 'parsley',
  'dill': 'dill',
  'sage': 'sage',
  'tarragon': 'tarragon',

  // --- Generic (checked after composites) ---
  garlic: 'garlic',
  onion: 'onion',
  carrot: 'carrot',
  mushroom: 'mushroom',
  egg: 'egg',
  cheese: 'cheese',
  lemon: 'lemon',
  bread: 'bread',
  chicken: 'chicken',
  fish: 'fish',
  rice: 'rice',
  spaghetti: 'spaghetti',
  pasta: 'pasta',
  honey: 'honey',
  milk: 'milk',
  flour: 'flour',
  tomato: 'tomato',
  beef: 'beef',
  pork: 'pork',
  cream: 'cream',
  stock: 'stock',
  bacon: 'bacon',
  guanciale: 'guanciale',
  pancetta: 'pancetta',
  oil: 'oil',
  butter: 'butter',
  cumin: 'cumin',
  thyme: 'thyme',
  paprika: 'paprika',
  cinnamon: 'cinnamon',
  avocado: 'avocado',
  corn: 'corn',
  potato: 'potato',
  broccoli: 'broccoli',
  spinach: 'spinach',
  celery: 'celery',
  ginger: 'ginger',
  chilli: 'chilli',
  cucumber: 'cucumber',
  capsicum: 'capsicum',
  zucchini: 'zucchini',
  peas: 'peas',
  lime: 'lime',
  orange: 'orange',
  apple: 'apple',
  banana: 'banana',
  coconut: 'coconut',
  lamb: 'lamb',
  prawns: 'prawns',
  tofu: 'tofu',
  yoghurt: 'yoghurt',
  parmesan: 'parmesan',
  sugar: 'sugar',
  salt: 'salt',
  pepper: 'pepper',
  vinegar: 'vinegar',
  mustard: 'mustard',
  oregano: 'oregano',
  basil: 'basil',
  rosemary: 'rosemary',
  nutmeg: 'nutmeg',
  turmeric: 'turmeric',
  vanilla: 'vanilla',
  chocolate: 'chocolate',
  wine: 'wine',
  water: 'water',
};

const BUCKET_BASE = `${import.meta.env.VITE_SUPABASE_URL}/storage/v1/object/public/ingredient-images`;

export function getIngredientImageUrl(item: string): string | null {
  const lower = item.toLowerCase();
  for (const [key, filename] of Object.entries(INGREDIENT_IMAGE_MAP)) {
    if (lower.includes(key)) {
      return `${BUCKET_BASE}/${filename}.png`;
    }
  }
  return null;
}

export const FALLBACK_EMOJI = '🥘';
