/**
 * Local keyword-based ingredient categorisation.
 * Replaces the Groq LLM edge function with a fast, deterministic lookup.
 */

type Category =
  | 'Produce'
  | 'Meat & Seafood'
  | 'Dairy & Eggs'
  | 'Bakery'
  | 'Pantry & Dry Goods'
  | 'Canned & Jarred'
  | 'Frozen'
  | 'Condiments & Sauces'
  | 'Spices & Seasonings'
  | 'Drinks'
  | 'Other';

// ── Multi-word phrases checked FIRST (order matters for ambiguity) ──────────
// These are checked before single-keyword matching so that e.g. "coconut milk"
// resolves to Canned & Jarred rather than Dairy.
const PHRASE_RULES: [string, Category][] = [
  // Substring-safety: these must match before shorter keywords like "pepper", "corn", "butter", "milk"
  ['peppercorn', 'Spices & Seasonings'],
  ['buttermilk', 'Dairy & Eggs'],

  // Canned & Jarred — check before Dairy/Produce to win ties
  ['coconut milk', 'Canned & Jarred'],
  ['coconut cream', 'Canned & Jarred'],
  ['tomato paste', 'Canned & Jarred'],
  ['tomato sauce', 'Canned & Jarred'],
  ['tomato puree', 'Canned & Jarred'],
  ['crushed tomato', 'Canned & Jarred'],
  ['diced tomato', 'Canned & Jarred'],
  ['chopped tomato', 'Canned & Jarred'],
  ['whole tomato', 'Canned & Jarred'],
  ['canned tomato', 'Canned & Jarred'],
  ['tinned tomato', 'Canned & Jarred'],
  ['sun-dried tomato', 'Canned & Jarred'],
  ['sundried tomato', 'Canned & Jarred'],
  ['peanut butter', 'Canned & Jarred'],
  ['almond butter', 'Canned & Jarred'],
  ['cashew butter', 'Canned & Jarred'],
  ['chicken broth', 'Canned & Jarred'],
  ['beef broth', 'Canned & Jarred'],
  ['vegetable broth', 'Canned & Jarred'],
  ['chicken stock', 'Canned & Jarred'],
  ['beef stock', 'Canned & Jarred'],
  ['vegetable stock', 'Canned & Jarred'],
  ['canned bean', 'Canned & Jarred'],
  ['canned chickpea', 'Canned & Jarred'],
  ['canned corn', 'Canned & Jarred'],
  ['canned tuna', 'Canned & Jarred'],

  // Condiments & Sauces — check before generic keywords
  ['soy sauce', 'Condiments & Sauces'],
  ['fish sauce', 'Condiments & Sauces'],
  ['oyster sauce', 'Condiments & Sauces'],
  ['hoisin sauce', 'Condiments & Sauces'],
  ['hot sauce', 'Condiments & Sauces'],
  ['chili sauce', 'Condiments & Sauces'],
  ['chilli sauce', 'Condiments & Sauces'],
  ['sweet chili sauce', 'Condiments & Sauces'],
  ['sweet chilli sauce', 'Condiments & Sauces'],
  ['bbq sauce', 'Condiments & Sauces'],
  ['barbecue sauce', 'Condiments & Sauces'],
  ['teriyaki sauce', 'Condiments & Sauces'],
  ['worcestershire sauce', 'Condiments & Sauces'],
  ['worcestershire', 'Condiments & Sauces'],
  ['tabasco', 'Condiments & Sauces'],
  ['sriracha', 'Condiments & Sauces'],
  ['sambal', 'Condiments & Sauces'],
  ['sambal oelek', 'Condiments & Sauces'],
  ['rice vinegar', 'Condiments & Sauces'],
  ['balsamic vinegar', 'Condiments & Sauces'],
  ['apple cider vinegar', 'Condiments & Sauces'],
  ['red wine vinegar', 'Condiments & Sauces'],
  ['white wine vinegar', 'Condiments & Sauces'],
  ['sesame oil', 'Condiments & Sauces'],

  // Spices & Seasonings — multi-word spice blends
  ['chili powder', 'Spices & Seasonings'],
  ['chilli powder', 'Spices & Seasonings'],
  ['chili flake', 'Spices & Seasonings'],
  ['chilli flake', 'Spices & Seasonings'],
  ['red pepper flake', 'Spices & Seasonings'],
  ['curry powder', 'Spices & Seasonings'],
  ['curry paste', 'Spices & Seasonings'],
  ['garam masala', 'Spices & Seasonings'],
  ['five spice', 'Spices & Seasonings'],
  ['five-spice', 'Spices & Seasonings'],
  ['onion powder', 'Spices & Seasonings'],
  ['garlic powder', 'Spices & Seasonings'],
  ['garlic salt', 'Spices & Seasonings'],
  ['celery salt', 'Spices & Seasonings'],
  ['bay leaf', 'Spices & Seasonings'],
  ['bay leaves', 'Spices & Seasonings'],
  ['black pepper', 'Spices & Seasonings'],
  ['white pepper', 'Spices & Seasonings'],
  ['ground pepper', 'Spices & Seasonings'],
  ['dried oregano', 'Spices & Seasonings'],
  ['dried thyme', 'Spices & Seasonings'],
  ['dried basil', 'Spices & Seasonings'],
  ['dried rosemary', 'Spices & Seasonings'],
  ['dried parsley', 'Spices & Seasonings'],
  ['dried dill', 'Spices & Seasonings'],
  ['ground cumin', 'Spices & Seasonings'],
  ['ground coriander', 'Spices & Seasonings'],
  ['ground cinnamon', 'Spices & Seasonings'],
  ['ground turmeric', 'Spices & Seasonings'],
  ['ground ginger', 'Spices & Seasonings'],
  ['ground nutmeg', 'Spices & Seasonings'],
  ['ground cloves', 'Spices & Seasonings'],
  ['ground cardamom', 'Spices & Seasonings'],
  ['smoked paprika', 'Spices & Seasonings'],
  ['italian seasoning', 'Spices & Seasonings'],
  ['mixed herbs', 'Spices & Seasonings'],
  ['herbes de provence', 'Spices & Seasonings'],
  ['cajun seasoning', 'Spices & Seasonings'],
  ['old bay', 'Spices & Seasonings'],
  ['everything bagel seasoning', 'Spices & Seasonings'],

  // Pantry — multi-word items
  ['olive oil', 'Pantry & Dry Goods'],
  ['vegetable oil', 'Pantry & Dry Goods'],
  ['canola oil', 'Pantry & Dry Goods'],
  ['coconut oil', 'Pantry & Dry Goods'],
  ['avocado oil', 'Pantry & Dry Goods'],
  ['cooking spray', 'Pantry & Dry Goods'],
  ['baking powder', 'Pantry & Dry Goods'],
  ['baking soda', 'Pantry & Dry Goods'],
  ['bicarbonate of soda', 'Pantry & Dry Goods'],
  ['maple syrup', 'Pantry & Dry Goods'],
  ['corn syrup', 'Pantry & Dry Goods'],
  ['vanilla extract', 'Pantry & Dry Goods'],
  ['vanilla essence', 'Pantry & Dry Goods'],
  ['almond extract', 'Pantry & Dry Goods'],
  ['chocolate chip', 'Pantry & Dry Goods'],
  ['bread crumb', 'Pantry & Dry Goods'],
  ['breadcrumb', 'Pantry & Dry Goods'],
  ['panko', 'Pantry & Dry Goods'],
  ['puff pastry', 'Pantry & Dry Goods'],
  ['filo pastry', 'Pantry & Dry Goods'],
  ['phyllo dough', 'Pantry & Dry Goods'],
  ['pie crust', 'Pantry & Dry Goods'],
  ['brown sugar', 'Pantry & Dry Goods'],
  ['caster sugar', 'Pantry & Dry Goods'],
  ['icing sugar', 'Pantry & Dry Goods'],
  ['powdered sugar', 'Pantry & Dry Goods'],
  ['confectioner sugar', 'Pantry & Dry Goods'],
  ['brown rice', 'Pantry & Dry Goods'],
  ['white rice', 'Pantry & Dry Goods'],
  ['basmati rice', 'Pantry & Dry Goods'],
  ['jasmine rice', 'Pantry & Dry Goods'],
  ['arborio rice', 'Pantry & Dry Goods'],
  ['wild rice', 'Pantry & Dry Goods'],
  ['rice noodle', 'Pantry & Dry Goods'],
  ['egg noodle', 'Pantry & Dry Goods'],
  ['dried pasta', 'Pantry & Dry Goods'],
  ['all-purpose flour', 'Pantry & Dry Goods'],
  ['all purpose flour', 'Pantry & Dry Goods'],
  ['plain flour', 'Pantry & Dry Goods'],
  ['self-raising flour', 'Pantry & Dry Goods'],
  ['self raising flour', 'Pantry & Dry Goods'],
  ['coconut flour', 'Pantry & Dry Goods'],
  ['almond flour', 'Pantry & Dry Goods'],
  ['almond meal', 'Pantry & Dry Goods'],

  // Dairy & Eggs — multi-word
  ['sour cream', 'Dairy & Eggs'],
  ['cream cheese', 'Dairy & Eggs'],
  ['heavy cream', 'Dairy & Eggs'],
  ['whipping cream', 'Dairy & Eggs'],
  ['double cream', 'Dairy & Eggs'],
  ['single cream', 'Dairy & Eggs'],
  ['thickened cream', 'Dairy & Eggs'],
  ['greek yogurt', 'Dairy & Eggs'],
  ['greek yoghurt', 'Dairy & Eggs'],
  ['creme fraiche', 'Dairy & Eggs'],
  ['crème fraîche', 'Dairy & Eggs'],
  ['parmesan cheese', 'Dairy & Eggs'],
  ['mozzarella cheese', 'Dairy & Eggs'],
  ['cheddar cheese', 'Dairy & Eggs'],
  ['feta cheese', 'Dairy & Eggs'],
  ['goat cheese', 'Dairy & Eggs'],
  ['cottage cheese', 'Dairy & Eggs'],

  // Produce — multi-word
  ['spring onion', 'Produce'],
  ['green onion', 'Produce'],
  ['red onion', 'Produce'],
  ['brown onion', 'Produce'],
  ['white onion', 'Produce'],
  ['yellow onion', 'Produce'],
  ['sweet potato', 'Produce'],
  ['bell pepper', 'Produce'],
  ['red pepper', 'Produce'],
  ['green pepper', 'Produce'],
  ['red capsicum', 'Produce'],
  ['green capsicum', 'Produce'],
  ['green bean', 'Produce'],
  ['snow pea', 'Produce'],
  ['sugar snap pea', 'Produce'],
  ['baby spinach', 'Produce'],
  ['bok choy', 'Produce'],
  ['pak choi', 'Produce'],
  ['bean sprout', 'Produce'],
  ['cherry tomato', 'Produce'],
  ['roma tomato', 'Produce'],
  ['grape tomato', 'Produce'],
  ['iceberg lettuce', 'Produce'],
  ['cos lettuce', 'Produce'],
  ['romaine lettuce', 'Produce'],
  ['butternut squash', 'Produce'],

  // Meat & Seafood — multi-word
  ['chicken breast', 'Meat & Seafood'],
  ['chicken thigh', 'Meat & Seafood'],
  ['chicken drumstick', 'Meat & Seafood'],
  ['chicken wing', 'Meat & Seafood'],
  ['chicken tender', 'Meat & Seafood'],
  ['chicken leg', 'Meat & Seafood'],
  ['whole chicken', 'Meat & Seafood'],
  ['ground beef', 'Meat & Seafood'],
  ['ground turkey', 'Meat & Seafood'],
  ['ground pork', 'Meat & Seafood'],
  ['ground chicken', 'Meat & Seafood'],
  ['beef mince', 'Meat & Seafood'],
  ['pork mince', 'Meat & Seafood'],
  ['lamb mince', 'Meat & Seafood'],
  ['pork belly', 'Meat & Seafood'],
  ['pork chop', 'Meat & Seafood'],
  ['pork loin', 'Meat & Seafood'],
  ['pork shoulder', 'Meat & Seafood'],
  ['lamb chop', 'Meat & Seafood'],
  ['lamb shank', 'Meat & Seafood'],
  ['lamb shoulder', 'Meat & Seafood'],
  ['beef brisket', 'Meat & Seafood'],
  ['beef chuck', 'Meat & Seafood'],
  ['beef sirloin', 'Meat & Seafood'],
  ['short rib', 'Meat & Seafood'],

  // Bakery — multi-word
  ['burger bun', 'Bakery'],
  ['hot dog bun', 'Bakery'],
  ['brioche bun', 'Bakery'],
  ['sourdough bread', 'Bakery'],
  ['white bread', 'Bakery'],
  ['wholemeal bread', 'Bakery'],
  ['whole wheat bread', 'Bakery'],
  ['garlic bread', 'Bakery'],

  // Drinks — multi-word
  ['sparkling water', 'Drinks'],
  ['tonic water', 'Drinks'],
  ['soda water', 'Drinks'],
  ['orange juice', 'Drinks'],
  ['apple juice', 'Drinks'],
  ['lemon juice', 'Produce'],   // lemon juice is fresh produce, not a drink
  ['lime juice', 'Produce'],    // same

  // Frozen
  ['frozen pea', 'Frozen'],
  ['frozen corn', 'Frozen'],
  ['frozen spinach', 'Frozen'],
  ['frozen berry', 'Frozen'],
  ['frozen fruit', 'Frozen'],
  ['frozen vegetable', 'Frozen'],
  ['frozen shrimp', 'Frozen'],
  ['frozen prawn', 'Frozen'],
  ['frozen fish', 'Frozen'],
  ['ice cream', 'Frozen'],
];

// ── Single keyword → category (checked after phrases) ───────────────────────
const KEYWORD_RULES: [string, Category][] = [
  // ── Produce ──
  ['onion', 'Produce'],
  ['garlic', 'Produce'],
  ['ginger', 'Produce'],
  ['shallot', 'Produce'],
  ['leek', 'Produce'],
  ['scallion', 'Produce'],
  ['chive', 'Produce'],
  ['tomato', 'Produce'],
  ['potato', 'Produce'],
  ['carrot', 'Produce'],
  ['celery', 'Produce'],
  ['broccoli', 'Produce'],
  ['cauliflower', 'Produce'],
  ['spinach', 'Produce'],
  ['kale', 'Produce'],
  ['lettuce', 'Produce'],
  ['arugula', 'Produce'],
  ['rocket', 'Produce'],
  ['cabbage', 'Produce'],
  ['cucumber', 'Produce'],
  ['zucchini', 'Produce'],
  ['courgette', 'Produce'],
  ['eggplant', 'Produce'],
  ['aubergine', 'Produce'],
  ['capsicum', 'Produce'],
  ['jalape', 'Produce'],     // jalapeño / jalapeno
  ['serrano', 'Produce'],
  ['habanero', 'Produce'],
  ['poblano', 'Produce'],
  ['mushroom', 'Produce'],
  ['asparagus', 'Produce'],
  ['artichoke', 'Produce'],
  ['beetroot', 'Produce'],
  ['beet', 'Produce'],
  ['radish', 'Produce'],
  ['turnip', 'Produce'],
  ['parsnip', 'Produce'],
  ['squash', 'Produce'],
  ['pumpkin', 'Produce'],
  ['corn', 'Produce'],
  ['pea', 'Produce'],
  ['edamame', 'Produce'],
  ['fennel', 'Produce'],
  ['watercress', 'Produce'],
  ['endive', 'Produce'],
  ['radicchio', 'Produce'],
  ['okra', 'Produce'],
  ['avocado', 'Produce'],
  ['lemon', 'Produce'],
  ['lime', 'Produce'],
  ['orange', 'Produce'],
  ['apple', 'Produce'],
  ['banana', 'Produce'],
  ['pear', 'Produce'],
  ['peach', 'Produce'],
  ['plum', 'Produce'],
  ['nectarine', 'Produce'],
  ['apricot', 'Produce'],
  ['mango', 'Produce'],
  ['pineapple', 'Produce'],
  ['papaya', 'Produce'],
  ['kiwi', 'Produce'],
  ['melon', 'Produce'],
  ['watermelon', 'Produce'],
  ['grape', 'Produce'],
  ['strawberr', 'Produce'],  // strawberry/strawberries
  ['blueberr', 'Produce'],
  ['raspberr', 'Produce'],
  ['blackberr', 'Produce'],
  ['cranberr', 'Produce'],
  ['cherry', 'Produce'],
  ['cherries', 'Produce'],
  ['fig', 'Produce'],
  ['pomegranate', 'Produce'],
  ['passionfruit', 'Produce'],
  ['coconut', 'Produce'],    // fresh coconut (coconut milk/cream handled by phrases)
  ['basil', 'Produce'],
  ['cilantro', 'Produce'],
  ['coriander', 'Produce'],  // fresh coriander (ground coriander handled by phrases)
  ['parsley', 'Produce'],
  ['mint', 'Produce'],
  ['rosemary', 'Produce'],
  ['thyme', 'Produce'],
  ['dill', 'Produce'],
  ['sage', 'Produce'],
  ['tarragon', 'Produce'],
  ['oregano', 'Produce'],
  ['chives', 'Produce'],
  ['lemongrass', 'Produce'],
  ['sprout', 'Produce'],

  // ── Meat & Seafood ──
  ['chicken', 'Meat & Seafood'],
  ['beef', 'Meat & Seafood'],
  ['steak', 'Meat & Seafood'],
  ['pork', 'Meat & Seafood'],
  ['lamb', 'Meat & Seafood'],
  ['veal', 'Meat & Seafood'],
  ['turkey', 'Meat & Seafood'],
  ['duck', 'Meat & Seafood'],
  ['goose', 'Meat & Seafood'],
  ['venison', 'Meat & Seafood'],
  ['bison', 'Meat & Seafood'],
  ['bacon', 'Meat & Seafood'],
  ['pancetta', 'Meat & Seafood'],
  ['prosciutto', 'Meat & Seafood'],
  ['chorizo', 'Meat & Seafood'],
  ['sausage', 'Meat & Seafood'],
  ['salami', 'Meat & Seafood'],
  ['pepperoni', 'Meat & Seafood'],
  ['ham', 'Meat & Seafood'],
  ['mince', 'Meat & Seafood'],
  ['ground meat', 'Meat & Seafood'],
  ['fish', 'Meat & Seafood'],
  ['salmon', 'Meat & Seafood'],
  ['tuna', 'Meat & Seafood'],
  ['cod', 'Meat & Seafood'],
  ['tilapia', 'Meat & Seafood'],
  ['snapper', 'Meat & Seafood'],
  ['barramundi', 'Meat & Seafood'],
  ['halibut', 'Meat & Seafood'],
  ['swordfish', 'Meat & Seafood'],
  ['mackerel', 'Meat & Seafood'],
  ['sardine', 'Meat & Seafood'],
  ['anchov', 'Meat & Seafood'],  // anchovy / anchovies
  ['shrimp', 'Meat & Seafood'],
  ['prawn', 'Meat & Seafood'],
  ['crab', 'Meat & Seafood'],
  ['lobster', 'Meat & Seafood'],
  ['mussel', 'Meat & Seafood'],
  ['clam', 'Meat & Seafood'],
  ['oyster', 'Meat & Seafood'],
  ['scallop', 'Meat & Seafood'],
  ['squid', 'Meat & Seafood'],
  ['calamari', 'Meat & Seafood'],
  ['octopus', 'Meat & Seafood'],

  // ── Dairy & Eggs ──
  ['milk', 'Dairy & Eggs'],
  ['cream', 'Dairy & Eggs'],
  ['butter', 'Dairy & Eggs'],
  ['cheese', 'Dairy & Eggs'],
  ['parmesan', 'Dairy & Eggs'],
  ['mozzarella', 'Dairy & Eggs'],
  ['cheddar', 'Dairy & Eggs'],
  ['gruyere', 'Dairy & Eggs'],
  ['brie', 'Dairy & Eggs'],
  ['feta', 'Dairy & Eggs'],
  ['ricotta', 'Dairy & Eggs'],
  ['mascarpone', 'Dairy & Eggs'],
  ['halloumi', 'Dairy & Eggs'],
  ['pecorino', 'Dairy & Eggs'],
  ['gouda', 'Dairy & Eggs'],
  ['provolone', 'Dairy & Eggs'],
  ['yogurt', 'Dairy & Eggs'],
  ['yoghurt', 'Dairy & Eggs'],
  ['egg', 'Dairy & Eggs'],
  ['ghee', 'Dairy & Eggs'],
  ['margarine', 'Dairy & Eggs'],

  // ── Bakery ──
  ['bread', 'Bakery'],
  ['tortilla', 'Bakery'],
  ['pita', 'Bakery'],
  ['naan', 'Bakery'],
  ['flatbread', 'Bakery'],
  ['wrap', 'Bakery'],
  ['bagel', 'Bakery'],
  ['croissant', 'Bakery'],
  ['baguette', 'Bakery'],
  ['ciabatta', 'Bakery'],
  ['focaccia', 'Bakery'],
  ['brioche', 'Bakery'],
  ['roll', 'Bakery'],
  ['bun', 'Bakery'],
  ['crumpet', 'Bakery'],
  ['english muffin', 'Bakery'],

  // ── Pantry & Dry Goods ──
  ['flour', 'Pantry & Dry Goods'],
  ['sugar', 'Pantry & Dry Goods'],
  ['rice', 'Pantry & Dry Goods'],
  ['pasta', 'Pantry & Dry Goods'],
  ['spaghetti', 'Pantry & Dry Goods'],
  ['penne', 'Pantry & Dry Goods'],
  ['fusilli', 'Pantry & Dry Goods'],
  ['rigatoni', 'Pantry & Dry Goods'],
  ['fettuccine', 'Pantry & Dry Goods'],
  ['linguine', 'Pantry & Dry Goods'],
  ['macaroni', 'Pantry & Dry Goods'],
  ['orzo', 'Pantry & Dry Goods'],
  ['lasagna', 'Pantry & Dry Goods'],
  ['lasagne', 'Pantry & Dry Goods'],
  ['noodle', 'Pantry & Dry Goods'],
  ['ramen', 'Pantry & Dry Goods'],
  ['udon', 'Pantry & Dry Goods'],
  ['soba', 'Pantry & Dry Goods'],
  ['vermicelli', 'Pantry & Dry Goods'],
  ['oat', 'Pantry & Dry Goods'],
  ['quinoa', 'Pantry & Dry Goods'],
  ['couscous', 'Pantry & Dry Goods'],
  ['polenta', 'Pantry & Dry Goods'],
  ['bulgur', 'Pantry & Dry Goods'],
  ['barley', 'Pantry & Dry Goods'],
  ['lentil', 'Pantry & Dry Goods'],
  ['chickpea', 'Pantry & Dry Goods'],
  ['bean', 'Pantry & Dry Goods'],
  ['cornstarch', 'Pantry & Dry Goods'],
  ['cornflour', 'Pantry & Dry Goods'],
  ['arrowroot', 'Pantry & Dry Goods'],
  ['tapioca', 'Pantry & Dry Goods'],
  ['gelatin', 'Pantry & Dry Goods'],
  ['gelatine', 'Pantry & Dry Goods'],
  ['yeast', 'Pantry & Dry Goods'],
  ['cocoa', 'Pantry & Dry Goods'],
  ['chocolate', 'Pantry & Dry Goods'],
  ['honey', 'Pantry & Dry Goods'],
  ['molasses', 'Pantry & Dry Goods'],
  ['treacle', 'Pantry & Dry Goods'],
  ['oil', 'Pantry & Dry Goods'],
  ['vinegar', 'Pantry & Dry Goods'],
  ['almond', 'Pantry & Dry Goods'],
  ['walnut', 'Pantry & Dry Goods'],
  ['pecan', 'Pantry & Dry Goods'],
  ['cashew', 'Pantry & Dry Goods'],
  ['pistachio', 'Pantry & Dry Goods'],
  ['hazelnut', 'Pantry & Dry Goods'],
  ['macadamia', 'Pantry & Dry Goods'],
  ['pine nut', 'Pantry & Dry Goods'],
  ['peanut', 'Pantry & Dry Goods'],
  ['sesame seed', 'Pantry & Dry Goods'],
  ['sunflower seed', 'Pantry & Dry Goods'],
  ['pumpkin seed', 'Pantry & Dry Goods'],
  ['chia seed', 'Pantry & Dry Goods'],
  ['flaxseed', 'Pantry & Dry Goods'],
  ['poppy seed', 'Pantry & Dry Goods'],
  ['raisin', 'Pantry & Dry Goods'],
  ['sultana', 'Pantry & Dry Goods'],
  ['currant', 'Pantry & Dry Goods'],
  ['dried fruit', 'Pantry & Dry Goods'],
  ['cereal', 'Pantry & Dry Goods'],
  ['granola', 'Pantry & Dry Goods'],
  ['cracker', 'Pantry & Dry Goods'],
  ['tortilla chip', 'Pantry & Dry Goods'],
  ['tofu', 'Pantry & Dry Goods'],
  ['tempeh', 'Pantry & Dry Goods'],

  // ── Canned & Jarred ──
  ['canned', 'Canned & Jarred'],
  ['tinned', 'Canned & Jarred'],
  ['passata', 'Canned & Jarred'],
  ['broth', 'Canned & Jarred'],
  ['stock', 'Canned & Jarred'],
  ['bouillon', 'Canned & Jarred'],
  ['olive', 'Canned & Jarred'],
  ['caper', 'Canned & Jarred'],
  ['pickle', 'Canned & Jarred'],
  ['gherkin', 'Canned & Jarred'],
  ['jam', 'Canned & Jarred'],
  ['preserve', 'Canned & Jarred'],
  ['marmalade', 'Canned & Jarred'],
  ['salsa', 'Canned & Jarred'],
  ['chutney', 'Canned & Jarred'],
  ['relish', 'Canned & Jarred'],

  // ── Condiments & Sauces ──
  ['ketchup', 'Condiments & Sauces'],
  ['mustard', 'Condiments & Sauces'],
  ['mayo', 'Condiments & Sauces'],
  ['mayonnaise', 'Condiments & Sauces'],
  ['tahini', 'Condiments & Sauces'],
  ['miso', 'Condiments & Sauces'],
  ['hoisin', 'Condiments & Sauces'],
  ['harissa', 'Condiments & Sauces'],
  ['pesto', 'Condiments & Sauces'],
  ['dressing', 'Condiments & Sauces'],
  ['marinade', 'Condiments & Sauces'],
  ['glaze', 'Condiments & Sauces'],

  // ── Spices & Seasonings ──
  ['salt', 'Spices & Seasonings'],
  ['pepper', 'Spices & Seasonings'],
  ['cumin', 'Spices & Seasonings'],
  ['paprika', 'Spices & Seasonings'],
  ['cinnamon', 'Spices & Seasonings'],
  ['nutmeg', 'Spices & Seasonings'],
  ['turmeric', 'Spices & Seasonings'],
  ['cardamom', 'Spices & Seasonings'],
  ['clove', 'Spices & Seasonings'],
  ['allspice', 'Spices & Seasonings'],
  ['saffron', 'Spices & Seasonings'],
  ['cayenne', 'Spices & Seasonings'],
  ['sumac', 'Spices & Seasonings'],
  ['za\'atar', 'Spices & Seasonings'],
  ['zaatar', 'Spices & Seasonings'],
  ['ras el hanout', 'Spices & Seasonings'],
  ['star anise', 'Spices & Seasonings'],
  ['vanilla', 'Spices & Seasonings'],
  ['extract', 'Spices & Seasonings'],
  ['seasoning', 'Spices & Seasonings'],
  ['spice', 'Spices & Seasonings'],

  // ── Drinks ──
  ['wine', 'Drinks'],
  ['beer', 'Drinks'],
  ['juice', 'Drinks'],
  ['coffee', 'Drinks'],
  ['tea', 'Drinks'],
  ['soda', 'Drinks'],
  ['cola', 'Drinks'],
  ['lemonade', 'Drinks'],
  ['kombucha', 'Drinks'],

  // ── Frozen ──
  ['frozen', 'Frozen'],
  ['ice cream', 'Frozen'],
];

/**
 * Classify a single ingredient name into a shopping aisle category.
 * Returns "Other" only when no keyword matches.
 */
export function classifyIngredient(itemName: string): Category {
  const name = itemName.toLowerCase().trim();
  if (!name) return 'Other';

  // Phase 1: multi-word phrase matching (most specific, wins ties)
  for (const [phrase, category] of PHRASE_RULES) {
    if (name.includes(phrase)) return category;
  }

  // Phase 2: single-keyword substring matching
  for (const [keyword, category] of KEYWORD_RULES) {
    if (name.includes(keyword)) return category;
  }

  return 'Other';
}
